const shortid = require("shortid");
const URL =  require("../models/urlModel")


/**
 * Creates a new url in the database
 * POST
 * {
 *  "shortId": "vsrgg45ge",  //generated by shortid
 *  "originalUrl": "http://www.google.com"
 * }
 */
const newShortUrl = async (req, res) =>{
    const {url} = req.body;
    if(!url){
        return res.status(400).json({ msg: "url is required" });
    }
    const shortID = shortid()
    await URL.create({
        shortId : shortID,
        redirectUrl: url
    })
    return  res.status(200).json({"Original Url": url, "shortened Url ": "http://localhost:8000/"+shortID });
}

/**
 * Gets url from the DB
 * GET
 * PARAMS: /:shortId
 */

const redirectUrl = async (req, res) =>{
    const shortId = req.params.shortId;
    const Url = await URL.findOne({shortId})
    if(!Url){
        return res.status(400).json({ msg: "url is not valid" });
    }
    res.status(200).json({"Oroginal Url":Url.redirectUrl})

}

module.exports={
    newShortUrl,
    redirectUrl
}